//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model1.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string Name { get; set; }
        public string inventory_code { get; set; }
        public float Price { get; set; }
        public int Amount { get; set; }
        public Nullable<int> IdWorkplace { get; set; }
    
        public virtual Workplaces Workplaces { get; set; }
    }
}
